// <auto-generated />
namespace Company1.Department1.Project1.AuthenticationService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tokens : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tokens));
        
        string IMigrationMetadata.Id
        {
            get { return "201701151550246_Tokens"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
